# Generated by Django 6.0.2 on 2026-03-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_liveprogram_passwordresetotp_is_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveprogram',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='liveprogram',
            name='hls_playlist_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='liveprogram',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
    ]
