# Generated by Django 6.0.2 on 2026-03-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_liveprogram_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveprogram',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveprogram',
            name='viewers_count',
            field=models.IntegerField(default=0),
        ),
    ]
