# Generated by Django 6.0.2 on 2026-04-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_liveprogram_likes_liveprogram_viewers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveprogram',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/live/'),
        ),
    ]
