# Generated by Django 6.0.2 on 2026-06-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_liveprogram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveprogram',
            name='shares_count',
            field=models.IntegerField(default=0),
        ),
    ]
